'use client';
import ContentTopNavTwo from "@/components/shared/main-nav-two/ContentTopNavTwo";
import {header2NavigationData} from "../../../data/navigation-items";
import Image from "next/image";
import { useRef, useState, useEffect } from "react";
import cx from 'classnames';

const OffCanvasThreeComponent = ({ isDropdownToggleSwitchOn, offCanvasRef, isDrawerOpen, setIsDrawerOpen, handleDrawerOpen, handleDrawerClose, trapKeyBoardMobileNav }) => {
    const searchToggleRef = useRef(null);
    const [isSearchWrapperOpen, setIsSearchWrapperOpen] = useState(false);

    // Directly target the #searchWrapper element within the iframe's DOM
    const searchWrapper = document.querySelector("#searchWrapper");
    const searchInput = document.querySelector('#searchWrapper .searchInput');
    const searchBtn = document.querySelector('#searchWrapper .searchBtn');
    const searchCloseBtn = document.querySelector('#searchWrapper .closeSearch a');

    //useEffect(() => {
    //    console.log('OffCanvasThreeComponent re-rendered');
    //    console.log('isDropdownToggleSwitchOn in OffCanvasThreeComponent:', isDropdownToggleSwitchOn);
    //    return () => {
    //        console.log('OffCanvasThreeComponent unmounted');
    //    };
    //}, [isDropdownToggleSwitchOn]);

    const handleSearchToggle = (event) => {
        event.preventDefault();
        
        if (isSearchWrapperOpen) {
            searchWrapper.classList.add("noShow");
            searchWrapper.classList.remove("show");
            searchWrapper.setAttribute('aria-expanded', 'false');
            searchInput.setAttribute('tabindex', '-1');
            searchBtn.setAttribute('tabindex', '-1');
            searchCloseBtn.setAttribute('tabindex', '-1');
            searchToggleRef.current.focus();
        } else {
            searchWrapper.classList.remove("noShow");
            searchWrapper.classList.add("show");
            searchWrapper.setAttribute('aria-expanded', 'true');
            searchInput.setAttribute('tabindex', '0');
            searchBtn.setAttribute('tabindex', '0');
            searchCloseBtn.setAttribute('tabindex', '0');
            searchInput.focus();
        }
        
        setIsSearchWrapperOpen((prevState) => !prevState);
    };

    const handleCloseSearch = () => {
        if (isSearchWrapperOpen) {

            searchWrapper.classList.add("noShow");
            searchWrapper.classList.remove("show");
            searchWrapper.setAttribute('aria-expanded', 'false');
            searchInput.setAttribute('tabindex', '-1');
            searchBtn.setAttribute('tabindex', '-1');
            searchCloseBtn.setAttribute('tabindex', '-1');
            searchToggleRef.current.focus();
        }
        setIsSearchWrapperOpen(false);
    };

    // Manages Search Buttons
    useEffect(() => {

        if (searchCloseBtn) {
            searchCloseBtn.addEventListener('click', handleCloseSearch);
        }

        return () => {
            if (searchCloseBtn) {
                searchCloseBtn.removeEventListener('click', handleCloseSearch);
            }
        };
    }, [isSearchWrapperOpen]);





    return ( 
        <header
            className={cx(
                'structHead',
                'imod-header-3',
                'offcanvas', 
                { dropdown: isDropdownToggleSwitchOn }
            )}
            role="banner"
            id="top"
            data-sectionname="header-3"
        >
            <div className="mainHeaderWrap">
                <div className="container">
                    <div className="row">
                        <div className="col-xs-9 col-sm-6 col-md-3 headLogo" id="ContentLogo" runat="server">
                            {/*<!-- Logo filename must be "logo.png" - The print version "logo-print.jpg" will get auto-generated by the build task -->*/}
                            <div className="hidden-print">
                                <a href="#">
                                    <Image
                                        src="/logo.png" 
                                        alt="Home" 
                                        className="darkTxt"
                                        width={2704}
                                        height={625}
                                        style={{width: '100%'}}
                                        priority
                                    />
                                    <Image 
                                        src="/logo-white.png" 
                                        alt="Home" 
                                        className="whiteTxt"
                                        width={2704}
                                        height={625}
                                        style={{width: '100%'}}
                                    />
                                </a>
                            </div>
                        </div>
                        <div className="col-xs-3 col-sm-6 col-md-9 headRight">
                            <div className="row hidden-sm hidden-xs">
                                {/*<!-- Desktop Navigation Bar -->*/}
                                <div className="desktopNav hidden-sm hidden-xs">
                                    <ContentTopNavTwo
                                        navItems={header2NavigationData}
                                        isDropDownToggleSwitchOn={isDropdownToggleSwitchOn}
                                    />
                                    <div id="ContentSearchDesktop" runat="server" className="search-desktop">
                                        <div className="searchToggle">
                                            <a 
                                                ref={searchToggleRef}
                                                aria-label="Toggle Site Search" 
                                                href="#" 
                                                id="searchToggleBtn" 
                                                role="button" 
                                                aria-expanded={isSearchWrapperOpen} 
                                                aria-controls="searchWrapper"
                                                onClick={handleSearchToggle}
                                            >
                                                <span className="fa fa-search"></span>
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div className="hidden-md hidden-lg">
                            <a 
                                    href="#" 
                                    role="button" 
                                    className={cx(
                                        'm-pikabu-nav-toggle', 
                                        'hidden-md', 
                                        'hidden-lg', 
                                        'js-offcanvas-trigger',
                                        'c-button', 
                                        { 'is-active': isDrawerOpen }
                                    )} 
                                    data-offcanvas-trigger="off-canvas" 
                                    aria-label="Open Mobile Navigation"
                                    aria-expanded={isDrawerOpen ? 'true' : 'false'}
                                    onClick={(e) => {
                                        e.preventDefault();
                                        handleDrawerOpen(offCanvasRef, setIsDrawerOpen, (event) =>
                                            trapKeyBoardMobileNav(event, offCanvasRef, () => handleDrawerClose(offCanvasRef, setIsDrawerOpen))
                                        );
                                    }}
                                >
                                    <span className="c-button__text">
                                        <span className="fa fa-bars"></span> Menu
                                    </span>
                                </a>
                                </div>
                        </div>
                        
                    </div>
                </div>
            </div>
        </header>
    );
}
 
export default OffCanvasThreeComponent;