import {Roboto, Montserrat} from 'next/font/google';
import '@fortawesome/fontawesome-free/css/all.css';
import '@fortawesome/fontawesome-free/css/v4-shims.css';
import "../../assets/css/vendor.css";
import "../../assets/css/globals.css";


const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});

const montserrat = Montserrat({
  variable: '--font-montserrat',
  subsets: ['latin'],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export function AspPlaceholder() {
  return (
    <div
      dangerouslySetInnerHTML={{
        __html: `
            <asp:placeholder runat="server" ID="SiteBuilder" Visible="False">
              <!-- SiteBuilder // -->
            </asp:placeholder>
            <asp:placeholder runat="server" ID="NavMaster" Visible="False">  
              <!-- NavMaster // -->
            </asp:placeholder>
        `,
      }}
    />
  );
}


export default function HomepageLayout({children}) {
  return (
    <html lang="en">
      <head >
        <meta charSet="utf-8" />
        <meta httpEquiv="X-UA-Compatible" content="IE=edge,chrome=1" />
        <title id="MainTitle" runat="server"></title>
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
        <meta name="robots" content="noindex" />



        <link rel="apple-touch-icon" sizes="180x180" href="images/apple-touch-icon.png" />



      </head>
      <body className={`${roboto.variable} ${montserrat.variable} home home-full`}>
        <form id="MainForm" method="post" runat="server">
          <AspPlaceholder />
          <div id="ContentAdminTools" runat="server" visible="false"></div>

          <a name="pagetop" aria-hidden="true"><span className="sr-only">Page Top</span></a>
          <div id="outer-wrap">
            <header className="structHead" role="banner" id="top">
              <div className="container-fluid">
                <div className="row">
                  <div className="col-xs-12 col-sm-6 col-md-6 headLogo" id="ContentLogo" runat="server"></div>
                  <div className="hidden-xs col-sm-6 col-md-6 breakpointViewBtns" id="ContentRightBtns" runat="server"></div>
                </div>
              </div>
            </header>

                    {children}

            <footer role="contentinfo">
              <div className="container-fluid">
                <div className="row">

                  <div id="ContentFooter" className="col-md-12" runat='server'>
                  </div>

                </div>
              </div>
            </footer>
          </div>
        </form>
      </body>
    </html>
  );
}
