'use client';
import ContentTopNavOne from "@/components/shared/main-nav-one/ContentTopNavOne";
import {header1NavigationData} from "@/data/navigation-items";
import Image from "next/image";
import { useRef, useState, useEffect } from "react";

const OffCanvasOneComponent = ({ isDropdownToggleSwitchOn, isSocialMediaToggleSwitchOff, offCanvasRef, isDrawerOpen, setIsDrawerOpen, handleDrawerOpen, handleDrawerClose, trapKeyBoardMobileNav }) => {
    const searchToggleRef = useRef(null);
    const [isSearchWrapperOpen, setIsSearchWrapperOpen] = useState(false);

    // Directly target the #searchWrapper element within the iframe's DOM
    const searchWrapper = document.querySelector("#searchWrapper");
    const searchInput = document.querySelector('#searchWrapper .searchInput');
    const searchBtn = document.querySelector('#searchWrapper .searchBtn');
    const searchCloseBtn = document.querySelector('#searchWrapper .closeSearch a');


    //useEffect(() => {
    //    console.log('OffCanvasOneComponent re-rendered');
    //    console.log('isDropdownToggleSwitchOn in OffCanvasOneComponent:', isDropdownToggleSwitchOn);
    //    return () => {
    //        console.log('OffCanvasOneComponent unmounted');
    //      };
    //}, [isDropdownToggleSwitchOn]);


    const handleSearchToggle = (event) => {
        event.preventDefault();
        
        if (isSearchWrapperOpen) {
            searchWrapper.classList.add("noShow");
            searchWrapper.classList.remove("show");
            searchWrapper.setAttribute('aria-expanded', 'false');
            searchInput.setAttribute('tabindex', '-1');
            searchBtn.setAttribute('tabindex', '-1');
            searchCloseBtn.setAttribute('tabindex', '-1');
            searchToggleRef.current.focus();
        } else {
            searchWrapper.classList.remove("noShow");
            searchWrapper.classList.add("show");
            searchWrapper.setAttribute('aria-expanded', 'true');
            searchInput.setAttribute('tabindex', '0');
            searchBtn.setAttribute('tabindex', '0');
            searchCloseBtn.setAttribute('tabindex', '0');
            searchInput.focus();
        }
        
        setIsSearchWrapperOpen((prevState) => !prevState);
    };

    const handleCloseSearch = () => {
        if (isSearchWrapperOpen) {

            searchWrapper.classList.add("noShow");
            searchWrapper.classList.remove("show");
            searchWrapper.setAttribute('aria-expanded', 'false');
            searchInput.setAttribute('tabindex', '-1');
            searchBtn.setAttribute('tabindex', '-1');
            searchCloseBtn.setAttribute('tabindex', '-1');
            searchToggleRef.current.focus();
        }
        setIsSearchWrapperOpen(false);
    };
    

    // Manages Search Buttons
    useEffect(() => {

        if (searchCloseBtn) {
            searchCloseBtn.addEventListener('click', handleCloseSearch);
        }

        return () => {
            if (searchCloseBtn) {
                searchCloseBtn.removeEventListener('click', handleCloseSearch);
            }
        };
    }, [isSearchWrapperOpen]);



    return ( 
        <header className={`structHead imod-header-1 offcanvas ${isDropdownToggleSwitchOn ? 'dropdown' : ''}`} role="banner" id="top" data-sectioname="header-1">
            <div className="mainHeaderWrap">
                <div className="container">
                    <div className="row">
                        <div className="col-xs-8 col-sm-4 col-md-5 headLogo" id="ContentLogo" runat="server">
                            {/* Logo filename must be "logo.png" - The print version "logo-print.jpg" will get auto-generated by the build task */}
                            <div className="hidden-print">
                                <a href="[URL:GROUP]">
                                  <Image 
                                        src="/logo.png" 
                                        alt="Home" 
                                        className="darkTxt"
                                        width={400}
                                        height={92}
                                        style={{maxWidth: '100%'}}
                                        priority
                                    />
                                </a>
                            </div>
                            <img loading="lazy" src="images/logo-print.jpg" className="visible-print" alt=""/>
                        </div>
                        <div className="col-xs-4 col-sm-8 col-md-7 headRight">
                            <div className="row">
                                <nav id="ContentUtilityNavNow" runat="server" className="col-xs-12 utilityNav hidden-xs hidden-sm imodSiteMap" aria-label="Utility">
                                    <ul>
                                        <li><a href="#">University Home</a></li>
                                        <li><a href="#">Alumni Association</a></li>
                                        <li><a href="#">Athletics</a></li>
                                        <li><a href="#">A-Z Campus Directory</a></li>
                                    </ul>
                                </nav>
                            </div>
                            <div className="row">
                                <div id="ContentHeaderSocial" runat="server" className="col-xs-12 headerSocial hidden-xs">
                                    {isSocialMediaToggleSwitchOff ? (
                                        <ul className="social">
                                            <li><a href="#" target="_blank" aria-label="Facebook"><span className="fa fa-facebook"></span></a></li>
                                            <li><a href="#" target="_blank" aria-label="Twitter"><span className="fa-brands fa-x-twitter"></span></a></li>
                                            <li><a href="#" target="_blank" aria-label="Instagram"><span className="fa fa-instagram"></span></a></li>
                                            <li><a href="#" target="_blank" aria-label="YouTube"><span className="fa fa-youtube"></span></a></li>
                                            <li><a href="#" target="_blank" aria-label="Flickr"><span className="fa fa-flickr"></span></a></li>
                                            <li className="searchToggle">
                                                <a 
                                                    ref={searchToggleRef}
                                                    aria-label="Toggle Site Search" 
                                                    href="#" 
                                                    id="searchToggleBtn" 
                                                    role="button" 
                                                    aria-expanded={isSearchWrapperOpen} 
                                                    aria-controls="searchWrapper"
                                                    onClick={handleSearchToggle}
                                                >
                                                    <span className="fa fa-search"></span>
                                                </a>
                                            </li>
                                        </ul>
                                    ) : (
                                        <ul className="social">
                                            <li className="searchToggle">
                                                <a 
                                                    ref={searchToggleRef}
                                                    aria-label="Toggle Site Search" 
                                                    href="#" 
                                                    id="searchToggleBtn" 
                                                    role="button" 
                                                    aria-expanded={isSearchWrapperOpen} 
                                                    aria-controls="searchWrapper"
                                                    onClick={handleSearchToggle}
                                                >
                                                    <span className="fa fa-search"></span>
                                                </a>
                                            </li>
                                        </ul>
                                    )}
                                </div>
                                <a 
                                    href="#" 
                                    role="button" 
                                    className={`m-pikabu-nav-toggle hidden-md hidden-lg js-offcanvas-trigger c-button ${isDrawerOpen ? 'is-active' : ''}`} 
                                    data-offcanvas-trigger="off-canvas" 
                                    aria-label="Open Mobile Navigation"
                                    aria-expanded={isDrawerOpen ? 'true' : 'false'}
                                    onClick={(e) => {
                                        e.preventDefault();
                                        handleDrawerOpen(offCanvasRef, setIsDrawerOpen, (event) => trapKeyBoardMobileNav(event, offCanvasRef, () => handleDrawerClose(offCanvasRef, setIsDrawerOpen)));
                                    }}
                                >
                                    <span className="c-button__text">
                                        <span className="fa fa-bars"></span> Menu
                                    </span>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            {/* Desktop Navigation Bar */}
            <div className="desktopNav hidden-sm hidden-xs">
                <div className="container">
                    <div className="row">
                        <ContentTopNavOne
                            navItems={header1NavigationData}
                            isDropDownToggleSwitchOn={isDropdownToggleSwitchOn}
                        />
                    </div>
                </div>
            </div>
        </header>
    );
}
 
export default OffCanvasOneComponent;