import ContentTopNavOne from "@/components/shared/main-nav-one/ContentTopNavOne";
import {header1NavigationData} from "@/data/navigation-items";
import Image from "next/image";
import { useRef, useState, useEffect } from "react";

const OffCanvasFourComponent =({ isDropdownToggleSwitchOn, isSocialMediaToggleSwitchOff, offCanvasRef, isDrawerOpen, setIsDrawerOpen, handleDrawerOpen, handleDrawerClose, trapKeyBoardMobileNav })  => {
    const searchToggleRef = useRef(null);
    const [isSearchWrapperOpen, setIsSearchWrapperOpen] = useState(false);

    // Directly target the #searchWrapper element within the iframe's DOM
    const searchWrapper = document.querySelector("#searchWrapper");
    const searchInput = document.querySelector('#searchWrapper .searchInput');
    const searchBtn = document.querySelector('#searchWrapper .searchBtn');
    const searchCloseBtn = document.querySelector('#searchWrapper .closeSearch a');

    //useEffect(() => {
    //    console.log('OffCanvasFourComponent re-rendered');
    //    console.log('isDropdownToggleSwitchOn in OffCanvasFourComponent:', isDropdownToggleSwitchOn);
    //}, [isDropdownToggleSwitchOn]);

    const handleSearchToggle = (event) => {
        event.preventDefault();
        
        if (isSearchWrapperOpen) {
            searchWrapper.classList.add("noShow");
            searchWrapper.classList.remove("show");
            searchWrapper.setAttribute('aria-expanded', 'false');
            searchInput.setAttribute('tabindex', '-1');
            searchBtn.setAttribute('tabindex', '-1');
            searchCloseBtn.setAttribute('tabindex', '-1');
            searchToggleRef.current.focus();
        } else {
            searchWrapper.classList.remove("noShow");
            searchWrapper.classList.add("show");
            searchWrapper.setAttribute('aria-expanded', 'true');
            searchInput.setAttribute('tabindex', '0');
            searchBtn.setAttribute('tabindex', '0');
            searchCloseBtn.setAttribute('tabindex', '0');
            searchInput.focus();
        }
        
        setIsSearchWrapperOpen((prevState) => !prevState);
    };

    const handleCloseSearch = () => {
        if (isSearchWrapperOpen) {

            searchWrapper.classList.add("noShow");
            searchWrapper.classList.remove("show");
            searchWrapper.setAttribute('aria-expanded', 'false');
            searchInput.setAttribute('tabindex', '-1');
            searchBtn.setAttribute('tabindex', '-1');
            searchCloseBtn.setAttribute('tabindex', '-1');
            searchToggleRef.current.focus();
        }
        setIsSearchWrapperOpen(false);
    };

    // Manages Search Buttons
    useEffect(() => {

        if (searchCloseBtn) {
            searchCloseBtn.addEventListener('click', handleCloseSearch);
        }

        return () => {
            if (searchCloseBtn) {
                searchCloseBtn.removeEventListener('click', handleCloseSearch);
            }
        };
    }, [isSearchWrapperOpen]);




    return ( 
        <header className={`structHead imod-header-4 offcanvas ${isDropdownToggleSwitchOn ? 'dropdown' : ''}`} role="banner" id="top" data-sectionname="header-4">
            <div className="mainHeaderWrap">
                <div className="container">
                    <div className="row">
                        <div className="col-xs-9 col-sm-4 col-sm-push-4 col-md-4 col-md-push-4 headLogo" id="ContentLogo" runat="server">
                            {/*<!-- Logo filename must be "logo.png" - The print version "logo-print.jpg" will get auto-generated by the build task -->*/}
                            <div className="hidden-print">
                                <a href="#">
                                    <Image
                                        src="/logo.png" 
                                        alt="Home" 
                                        className="darkTxt"
                                        width={2704}
                                        height={625}
                                        style={{width: '100%'}}
                                        priority
                                    />
                                    <Image 
                                        src="/logo-white.png" 
                                        alt="Home" 
                                        className="whiteTxt"
                                        width={2704}
                                        height={625}
                                        style={{width: '100%'}}
                                    />
                                </a>
                            </div>
                        </div>
                        <div className="hidden-xs col-sm-4 col-sm-pull-4 col-md-4 col-md-push-4 headSocial">
                            <div className="row">
                                <div id="ContentHeaderSocial" runat="server" className="col-xs-12 headerSocial hidden-xs">
                                    {isSocialMediaToggleSwitchOff ? (
                                        <ul className="social">
                                            <li><a href="#" target="_blank" aria-label="Facebook"><span className="fa fa-facebook"></span></a></li>
                                            <li><a href="#" target="_blank" aria-label="Twitter"><span className="fa-brands fa-x-twitter"></span></a></li>
                                            <li><a href="#" target="_blank" aria-label="Instagram"><span className="fa fa-instagram"></span></a></li>
                                            <li><a href="#" target="_blank" aria-label="YouTube"><span className="fa fa-youtube"></span></a></li>
                                            <li><a href="#" target="_blank" aria-label="Flickr"><span className="fa fa-flickr"></span></a></li>
                                            <li className="searchToggle">
                                                <a 
                                                    ref={searchToggleRef}
                                                    aria-label="Toggle Site Search" 
                                                    href="#" 
                                                    id="searchToggleBtn" 
                                                    role="button" 
                                                    aria-expanded={isSearchWrapperOpen} 
                                                    aria-controls="searchWrapper"
                                                    onClick={handleSearchToggle}
                                                >
                                                    <span className="fa fa-search"></span>
                                                </a>
                                            </li>
                                        </ul>
                                    ) : (
                                        <ul className="social">
                                            <li className="searchToggle">
                                                <a 
                                                    ref={searchToggleRef}
                                                    aria-label="Toggle Site Search" 
                                                    href="#" 
                                                    id="searchToggleBtn" 
                                                    role="button" 
                                                    aria-expanded={isSearchWrapperOpen} 
                                                    aria-controls="searchWrapper"
                                                    onClick={handleSearchToggle}
                                                >
                                                    <span className="fa fa-search"></span>
                                                </a>
                                            </li>
                                        </ul>
                                    )}
                                </div>
                                
                            </div>
                        </div>
                        <div className="hidden-xs hidden-sm col-md-4 col-md-pull-8 address">
                            <div className="row">
                                <nav id="ContentAddress" runat="server" className="col-xs-12 hidden-xs hidden-sm">
                                    <p>12345 Street Name, City, KS<br/>123-456-7890</p>
                                </nav>
                            </div>
                        </div>
                        <div className="col-xs-3 col-sm-4 hidden-md hidden-lg toggleMenu">
                        <a 
                                    href="#" 
                                    role="button" 
                                    className={`m-pikabu-nav-toggle hidden-md hidden-lg js-offcanvas-trigger c-button ${isDrawerOpen ? 'is-active' : ''}`} 
                                    data-offcanvas-trigger="off-canvas" 
                                    aria-label="Open Mobile Navigation"
                                    aria-expanded={isDrawerOpen ? 'true' : 'false'}
                                    onClick={(e) => {
                                        e.preventDefault();
                                        handleDrawerOpen(offCanvasRef, setIsDrawerOpen, (event) => trapKeyBoardMobileNav(event, offCanvasRef, () => handleDrawerClose(offCanvasRef, setIsDrawerOpen)));
                                    }}
                                >
                                    <span className="c-button__text">
                                        <span className="fa fa-bars"></span> Menu
                                    </span>
                                </a>
                        </div>
                    </div>
                </div>
            </div>

            {/*<!-- Desktop Navigation Bar -->*/}
            <div className="desktopNav hidden-sm hidden-xs">
                <div className="container">
                    <div className="row">
                        <ContentTopNavOne
                            navItems={header1NavigationData}
                            isDropDownToggleSwitchOn={isDropdownToggleSwitchOn}
                        />
                    </div>
                </div>
            </div>
        </header>
    );
}
 
export default OffCanvasFourComponent;